AWSTemplateFormatVersion: 2010-09-09
Description: Subnet Creation for Pronto VPC
Parameters:
  StackParameter:
    Type: String
    Default: Please enter the correct stack name

Resources:
  # Public subnets for 2 VPC's, one for each
  PublicSubnet1:
    Type: 'AWS::EC2::Subnet'
    Properties:
      VpcId: !ImportValue
        'Fn::Sub': '${StackParameter}-VPC1'
      CidrBlock: 10.48.160.0/28
      AvailabilityZone: !Join
        - ''
        - - !Ref 'AWS::Region'
          - b
      Tags:
        - Key: Name
          Value: !Sub ${AWS::StackName}-Public-1
  PublicSubnet2:
    Type: 'AWS::EC2::Subnet'
    Properties:
      VpcId: !ImportValue
        'Fn::Sub': '${StackParameter}-VPC2'
      CidrBlock: 10.48.160.64/28
      AvailabilityZone: !Join
        - ''
        - - !Ref 'AWS::Region'
          - b
      Tags:
        - Key: Name
          Value: !Sub ${AWS::StackName}-Public-2

  # Private subnets for 2 VPC's, 3 for each
  PrivateSubnet1VPC1:
    Type: 'AWS::EC2::Subnet'
    Properties:
      VpcId: !ImportValue
        'Fn::Sub': '${StackParameter}-VPC1'
      CidrBlock: 10.48.160.16/28
      AvailabilityZone: !Join
        - ''
        - - !Ref 'AWS::Region'
          - b
      Tags:
        - Key: Name
          Value: !Sub ${AWS::StackName}-VPC-1-Private-1
  PrivateSubnet2VPC1:
    Type: 'AWS::EC2::Subnet'
    Properties:
      VpcId: !ImportValue
        'Fn::Sub': '${StackParameter}-VPC1'
      CidrBlock: 10.48.160.32/28
      AvailabilityZone: !Join
        - ''
        - - !Ref 'AWS::Region'
          - b
      Tags:
        - Key: Name
          Value: !Sub ${AWS::StackName}-VPC-1-Private-2
  PrivateSubnet3VPC1:
    Type: 'AWS::EC2::Subnet'
    Properties:
      VpcId: !ImportValue
        'Fn::Sub': '${StackParameter}-VPC1'
      CidrBlock: 10.48.160.48/28
      AvailabilityZone: !Join
        - ''
        - - !Ref 'AWS::Region'
          - b
      Tags:
        - Key: Name
          Value: !Sub ${AWS::StackName}-VPC-1-Private-3
  PrivateSubnet1VPC2:
    Type: 'AWS::EC2::Subnet'
    Properties:
      VpcId: !ImportValue
        'Fn::Sub': '${StackParameter}-VPC2'
      CidrBlock: 10.48.160.80/28
      AvailabilityZone: !Join
        - ''
        - - !Ref 'AWS::Region'
          - b
      Tags:
        - Key: Name
          Value: !Sub ${AWS::StackName}-VPC-2-Private-1
  PrivateSubnet2VPC2:
      Type: 'AWS::EC2::Subnet'
      Properties:
        VpcId: !ImportValue
          'Fn::Sub': '${StackParameter}-VPC2'
        CidrBlock: 10.48.160.96/28
        AvailabilityZone: !Join
          - ''
          - - !Ref 'AWS::Region'
            - b
        Tags:
          - Key: Name
            Value: !Sub ${AWS::StackName}-VPC-2-Private-2
  PrivateSubnet3VPC2:
      Type: 'AWS::EC2::Subnet'
      Properties:
        VpcId: !ImportValue
          'Fn::Sub': '${StackParameter}-VPC2'
        CidrBlock: 10.48.160.112/28
        AvailabilityZone: !Join
          - ''
          - - !Ref 'AWS::Region'
            - b
        Tags:
          - Key: Name
            Value: !Sub ${AWS::StackName}-VPC-2-Private-3
