#!/bin/bash

function InstallAdminPackages {
    yum install mlocate -y || echo "failed to install mlocate"
}

function CreateUsers {
    echo "Creating group for interactive users"
    groupadd pronto-group || echo "failed to add pronto group"
    
    UserList=(
        LiYu
        WarrenJohnson
        DiwakarGanapathy
        ArunHarimurthy
        SouvikPatra
    )

    echo "Creating the list of users needs to be created"
    for i in "${UserList[@]}"; do
        echo "Adding user ${i}"
        useradd ${i} -g pronto-group -G pronto-group || echo "Failed to add user ${i}"
    done

    echo "Include the list of users in sudoers"
    echo "# Include interactive users in sudo list" > 030_pronto_users
    for i in "${UserList[@]}"; do
        echo "Adding user ${i} in sudo list"
        echo "${i}        ALL=(ALL)       NOPASSWD: ALL" >> 030_pronto_users || echo "Failed to include user ${i} in sudo list"
    done

}

function InstallAWSClient {
    echo "Install unzip command"
    yum install unzip -y
    echo "Download and install the AWS CLI"
    mkdir awscli_install
    cd awscli_install
    curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
    unzip awscliv2.zip
    sudo ./aws/install -i /usr/local/aws-cli -b /usr/local/bin
    cd ~
}

function InstallOracleClient {
    echo "Download oracle client from s3"
    mkdir oracle_install
    cd oracle_install
    /usr/local/bin/aws s3 sync s3://pos-pronto-repository/oracle_client/ ./
    yum install oracle-instantclient18.5-*.rpm -y
    cd ~  

    echo "Include oracle vars"
    echo "# Oracle vars">>/etc/bashrc
    echo 'export ORACLE_HOME=/usr/lib/oracle/18.5/client64'>>/etc/bashrc
    echo 'export LD_LIBRARY_PATH="${ORACLE_HOME}/lib:/pro/pronto/xmllib"'>>/etc/bashrc
    echo 'export PATH="${PATH}:${ORACLE_HOME}/bin/"'>>/etc/bashrc

}

function ConfigureOracleClient {
    echo "create network directory"
    mkdir -p /usr/lib/oracle/18.5/client64/network/admin/
    echo '# sqlnet.ora Network Configuration File: C:\Users\Administrator\Documents\Apps\Oracle\product\18.0.0\client_1\NETWORK\ADMIN\sqlnet.ora
# Generated by Oracle configuration tools.

# This file is actually generated by netca. But if customers choose to
# install "Software Only", this file wont exist and without the native
# authentication, they will not be able to connect to the database on NT.

SQLNET.AUTHENTICATION_SERVICES= (NTS)

NAMES.DIRECTORY_PATH= (TNSNAMES, EZCONNECT)
' > /usr/lib/oracle/18.5/client64/network/admin/sqlnet.ora
    echo '# Oracle Connect Information
NEOPILDB=(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST=pronto-neopil-rds.cw2fbiosdu9v.ap-southeast-2.rds.amazonaws.com)(PORT=1521))(CONNECT_DATA=(SERVER=DEDICATED)(SERVICE_NAME=neopildb)))
' > /usr/lib/oracle/18.5/client64/network/admin/tnsnames.ora
}