  TransitGateway:
    Type: AWS::EC2::TransitGateway
    Properties:
      Description: TGW Route Integration for Test VPC
      AutoAcceptSharedAttachments: disable
      DefaultRouteTableAssociation: disable
      DefaultRouteTablePropagation: disable
      DnsSupport: enable
      VpnEcmpSupport: enable
      Tags: 
        - 
          Key: Name
          Value: !Sub '${AWS::StackName}-TGW'

  TransitGatewayAttachment:
    Type: AWS::EC2::TransitGatewayAttachment
    Properties:
      TransitGatewayId: !Ref TransitGateway
      Tags: 
        - 
          Key: Name
          Value: vf-pos-tgwa
      VpcId: !ImportValue
          'Fn::Sub': '${StackParameter}'
      SubnetIds: 
        - !Ref PrivateSubnetA
        - !Ref PrivateSubnetB
        - !Ref PrivateSubnetC