AWSTemplateFormatVersion: 2010-09-09
Parameters:
  VPCParameter:
    Type: String
    Default: vf-pos-test-vpc
  PrivateSubnetA:
    Type: String
    Default: vf-pos-test-subnet-PrivateA
  PrivateSubnetB:
    Type: String
    Default: vf-pos-test-subnet-PrivateB
  PrivateSubnetC:
    Type: String
    Default: vf-pos-test-subnet-PrivateC
Resources:
  EC2SecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: vh-pronto-test-ec2-sg
      GroupName: vh-pronto-test-ec2-sg
      VpcId: !ImportValue
        'Fn::Sub': '${VPCParameter}'
      Tags:
        - Key: Name
          Value: SecurityGroupForProntoEC2
        - Key: Environment
          Value: Test
      SecurityGroupIngress:
        - CidrIp: 10.48.160.0/25
          Description: HTTP Only
          FromPort: 80
          IpProtocol: tcp
          ToPort: 80
        - CidrIp: 10.48.160.0/25
          Description: SSH Only
          FromPort: 22
          IpProtocol: tcp
          ToPort: 22
        - CidrIp: 10.48.160.0/25
          Description: HTTPS Only
          FromPort: 443
          IpProtocol: tcp
          ToPort: 443
  NPEEC2Instance:
    Type: 'AWS::EC2::Instance'
    Properties:
      ImageId: ami-0d092fa585cd2ebe2
      InstanceType: m5.large
      KeyName: pronto-app-servers
      Tenancy: default
      SubnetId: !ImportValue
        'Fn::Sub': '${PrivateSubnetA}'
      EbsOptimized: true
      SecurityGroupIds:
        - Ref: EC2SecurityGroup
      SourceDestCheck: true
      BlockDeviceMappings:
        - DeviceName: /dev/sda1
          Ebs:
            Encrypted: true
            VolumeSize: 200
            SnapshotId: snap-075023ef5a4cb1177
            VolumeType: gp2
            DeleteOnTermination: false
      IamInstanceProfile:
        Ref: Ec2InstanceSecurityGroupProfile
      Tags:
        - Key: Environment
          Value: Test
        - Key: Name
          Value: vf-pronto-npe-ec2
  PIEEC2Instance:
    Type: 'AWS::EC2::Instance'
    Properties:
      ImageId: ami-01448715c06d2edb5
      InstanceType: t3.medium
      KeyName: pronto-app-servers
      Tenancy: default
      SubnetId: !ImportValue
        'Fn::Sub': '${PrivateSubnetB}'
      EbsOptimized: true
      SecurityGroupIds:
        - Ref: EC2SecurityGroup
      SourceDestCheck: true
      BlockDeviceMappings:
        - DeviceName: /dev/sda1
          Ebs:
            Encrypted: true
            VolumeSize: 100
            SnapshotId: snap-093396680b7bd0fb8
            VolumeType: gp2
            DeleteOnTermination: false
      IamInstanceProfile:
        Ref: Ec2InstanceSecurityGroupProfile
      Tags:
        - Key: Environment
          Value: Test
        - Key: Name
          Value: vf-pronto-pie-pil-ec2
  NEOPILEC2Instance:
    Type: 'AWS::EC2::Instance'
    Properties:
      ImageId: ami-01448715c06d2edb5
      InstanceType: t3.medium
      KeyName: pronto-app-servers
      Tenancy: default
      SubnetId: !ImportValue
        'Fn::Sub': '${PrivateSubnetC}'
      EbsOptimized: true
      SecurityGroupIds:
        - Ref: EC2SecurityGroup
      SourceDestCheck: true
      BlockDeviceMappings:
        - DeviceName: /dev/sda1
          Ebs:
            Encrypted: true
            VolumeSize: 200
            SnapshotId: snap-093396680b7bd0fb8
            VolumeType: gp2
            DeleteOnTermination: false
      IamInstanceProfile:
        Ref: Ec2InstanceSecurityGroupProfile
      Tags:
        - Key: Environment
          Value: Test
        - Key: Name
          Value: vf-pronto-neopil-ec2
  Ec2InstanceSecurityGroupProfile:
    Type: 'AWS::IAM::InstanceProfile'
    Properties:
      Roles:
        - !Ref Ec2InstanceProfileRole
  Ec2InstanceProfileRole:
    Type: 'AWS::IAM::Role'
    Properties:
      Path: /
      Policies:
        - PolicyDocument:
            Statement:
              - Action:
                  - 'cloudwatch:PutMetricData'
                  - 'cloudwatch:GetMetricStatistics'
                  - 'cloudwatch:ListMetrics'
                  - 'ec2:DeleteVolume'
                  - 'ec2:DeleteSnapshot'
                  - 'ec2:DetachVolume'
                  - 'ec2:AttachVolume'
                  - 'ec2:CreateSnapshot'
                  - 'ec2:CreateVolume'
                  - 'ec2:CreateTags'
                  - 'ec2:DescribeSnapshots'
                  - 'ec2:DescribeInstances'
                  - 'ec2:DescribeVolumes'
                  - 'ec2:DescribeVpcs'
                  - 'route53:AssociateVPCWithHostedZone'
                Effect: Allow
                Resource: '*'
            Version: 2012-10-17
          PolicyName: prontotestec2instanceprofilerole-inline-policy
        - PolicyDocument:
            Statement:
              - Action:
                  - 'kms:Encrypt'
                  - 'kms:ReEncrypt*'
                  - 'kms:Decrypt'
                  - 'kms:GenerateDataKey*'
                  - 'kms:DescribeKey'
                  - 'kms:CreateGrant'
                Effect: Allow
                Resource: >-
                  arn:aws:kms:ap-southeast-2:650481372990:key/683a8ace-7822-490e-84fc-9ae8c651515d
            Version: 2012-10-17
          PolicyName: prontotestec2instanceprofilerole_kms-inline-policy
      RoleName: RoleForProntoEC2
      AssumeRolePolicyDocument:
        Statement:
          - Action: 'sts:AssumeRole'
            Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
        Version: 2012-10-17
      MaxSessionDuration: 3600
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/AmazonEC2ReadOnlyAccess'
        - 'arn:aws:iam::aws:policy/AmazonVPCReadOnlyAccess'
        - 'arn:aws:iam::aws:policy/AmazonRoute53ReadOnlyAccess'
        - 'arn:aws:iam::aws:policy/AmazonS3ReadOnlyAccess'
      Description: Allows EC2 instances to call AWS services on your behalf.
      Tags:
        - Key: Name
          Value: RoleForProntoEC2
        - Key: Environment
          Value: Test

Outputs:
  NPEEC2Instance:
    Value: !Ref NPEEC2Instance
    Description: NPEEC2Instance Name
    Export:
      Name:
        Fn::Sub: ${AWS::StackName}-NPE
  PIEEC2Instance:
    Value: !Ref PIEEC2Instance
    Description: PIEEC2Instance Name
    Export:
      Name:
        Fn::Sub: ${AWS::StackName}-PIE
  NEOPILEC2Instance:
    Value: !Ref NEOPILEC2Instance
    Description: NEOPILEC2Instance Name
    Export:
      Name:
        Fn::Sub: ${AWS::StackName}-NEOPIL
  EC2SecurityGroup:
    Value: !Ref EC2SecurityGroup
    Export:
      Name:
        Fn::Sub: ${AWS::StackName}-sg