AWSTemplateFormatVersion: 2010-09-09
Parameters:
  Environment:
    Type: String
    Default: test
  VPCParameter:
    Type: String
    Default: vf-pos-test-vpc
  PublicSubnetA:
    Type: String
    Default: vf-pos-test-subnet-PublicA

Resources:
  WinEc2InstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties: 
      GroupDescription: vf-pronto-windows-ec2-securitygroup
      GroupName: vf-pronto-windows-ec2-sg
      SecurityGroupIngress: 
        - CidrIp: 203.18.190.17/32
          Description: HTTPS only
          FromPort: 3389
          IpProtocol: TCP
          ToPort: 3389
        - CidrIp: 203.20.36.80/31
          Description: HTTPS only
          FromPort: 3389
          IpProtocol: TCP
          ToPort: 3389
        - CidrIp: 101.119.57.0/28
          Description: HTTPS only
          FromPort: 3389
          IpProtocol: TCP
          ToPort: 3389
        - CidrIp: 119.11.1.10/32
          Description: HTTPS only
          FromPort: 3389
          IpProtocol: TCP
          ToPort: 3389
      SecurityGroupEgress:
        - IpProtocol: TCP
          FromPort: 1521
          ToPort: 1521
          CidrIp: 10.48.160.0/25
        - IpProtocol: TCP
          FromPort: 22
          ToPort: 22
          CidrIp: 10.48.160.0/25
        - IpProtocol: TCP
          FromPort: 443
          ToPort: 443
          CidrIp: 10.0.0.0/8
        - IpProtocol: TCP
          FromPort: 3389
          ToPort: 3389
          CidrIp: 10.48.160.0/25
      Tags: 
        - Key: Environment
          Value: !Sub ${Environment}
        - Key: Name
          Value: !Sub vf-pos-bastion-sg-${Environment}
      VpcId: !ImportValue
        'Fn::Sub': '${VPCParameter}'

  WinBastionInstance:
    Type: AWS::EC2::Instance
    Properties:
      BlockDeviceMappings: 
        - DeviceName: /dev/sda1
          Ebs: 
            DeleteOnTermination: false
            Encrypted: true
            VolumeSize: 100
            VolumeType: gp2
      ImageId: ami-0659baaaa394eba5e
      InstanceType: t3.medium
      KeyName: pronto-bastion-key-pair
      NetworkInterfaces:
        - AssociatePublicIpAddress: True
          DeleteOnTermination: True
          DeviceIndex: 0
          SubnetId: !ImportValue
           'Fn::Sub': '${PublicSubnetA}'
          GroupSet: 
          - !Ref WinEc2InstanceSecurityGroup
      Tags: 
        - Key: Environment
          Value: !Sub ${Environment}
        - Key: Name
          Value: !Sub 'vf-pronto-win-bastion-${Environment}'