AWSTemplateFormatVersion: 2010-09-09
Description: VPC for VF-POS Pronto Upgrade
Parameters:
  VPCName:
    Description: Name of the VPC
    Type: String
    Default: vf-pos-test-vpc

  CIDRBlock:
    Description: CIDR block (subnet) for the VPC (eg 10.48.XX.0/YY)
    Type: String
    Default: 10.48.160.0/25
    ConstraintDescription: must be a valid CIDR block (subnet).

Resources:
  VPC:
    Type: 'AWS::EC2::VPC'
    Properties:
      CidrBlock: !Ref CIDRBlock
      EnableDnsSupport: 'true'
      EnableDnsHostnames: 'true'
      InstanceTenancy: default
      Tags:
        - Key: Name
          Value: !Ref "AWS::StackName"
        - Key: CIDR
          Value: !Ref CIDRBlock

Outputs:
  VPC:
    Description: VPC Details
    Value: !Ref VPC
    Export:
      Name: !Sub '${AWS::StackName}'
  CIDR:
    Description: CIDR Details
    Value: !Ref CIDRBlock
    Export:
      Name: !Sub '${AWS::StackName}-CIDR'



